### PR TITLE
Function name correction

### PR DESCRIPTION
**Pull request by buliasz**
RegisterCallback function was renamed to CallbackCreate in the v2.0-a090-ae96c4a version.

### CODE REVIEW

**Comment by mmikeww** [comment]
Hey thanks. We want to try to keep it backwards compatible with AHK v1 if possible.

Does the error happen at load time or run time? Do either of these work?

```autohotkey
Static EnumProc := (A_AhkVersion < "2") ? RegisterCallback("MDMF_EnumProc") 
                                        : CallbackCreate("MDMF_EnumProc") 
```

or

```autohotkey
Static CbFunc := (A_AhkVersion < "2") ? Func("RegisterCallback") 
                                      : Func("CallbackCreate") 
Static EnumProc := %CbFunc%("MDMF_EnumProc") 
```

Maybe @lexikos can give input?

**Comment by buliasz** [comment]
Hi Mike,

Well I'm not really interested in v1 backward compatibility. In my opinion it unnecessarily complicates the code (and slightly slows it down). So I'll leave those checks to others that are interested in v1 compatibility. 

Regards,
Bart

**Comment by mmikeww** [comment]
I agree it does complicate the code, but we've put in work on this front already, so I think its appropriate to continue. I'll take a look when I get a chance

**Comment by mmikeww** [comment]
I went with this:

```autohotkey
Static CbFunc := (A_AhkVersion < "2") ? Func("RegisterCallback") 
                                      : Func("CallbackCreate") 
Static EnumProc := %CbFunc%("MDMF_EnumProc") 
```

From brief testing it looks like it works with both v1 and v2

**Pull request closed without merging**
