### PR TITLE
Allow HBitmap to handle transparency

### PR DESCRIPTION
**Pull request by iseahound**
It's missing variable declarations for compatibility with #warn. I've never used Warn.

### CODE REVIEW

**Comment by mmikeww** [comment]
Have you tested it on both v1 and v2?

**Comment by iseahound** [comment]
It's compatible. It's all DllCall/NumPut/NumGet, very little is in AHK.

There's 2 functions: One of them goes hBitmap -> Bitmap and copies the alpha channel too. This function is about 120% slower than the built in Gdip_CreateBitmapfromHbitmap. 

The other one goes Bitmap -> hBitmap, and copies the alpha channel. It should be said that alpha channels aren't officially supported in device independent bitmaps - it just so happens that 32-bit RGB is fast as it allocates 4 bytes per pixel. This is much faster than squishing 1.3 pixels into an int. The reason why this is about 20% faster is that the built-in function Gdip_CreateHBitmapfromBitmap takes an argument "alpha" that is the replacement color for all transparent pixels. So whereas the built in function copies the color data, and does a replacement for all alpha pixels, this function only copies the color data, making it much faster. 

An example of hBitmap -> Bitmap would be copying the mouse cursor using DrawIcon. The cursor is an hBitmap with transparency. 

An example of Bitmap -> hBitmap would be for speed purposes only. It's just a faster conversion from pBitmap to hbm, and then it's a simple bitblt from the hbm to any device context.

**Comment by iseahound** [comment]
This is the image I use for testing. 

https://i.imgur.com/PBy1WBT.png

There is a subtle shadow along the edge, watch for changes in that.

**Comment by mmikeww** [comment]
Ok merged thanks a lot!

**Pull request merged**
